### ISSUE TITLE
 Inquiry About Access to the Million-IRD Dataset

### ISSUE THREAD

**Issue by Aitical** [akshaydudhane16/DyNet#1]
Nice work!

I am particularly interested in exploring the Million-IRD dataset for my own research endeavors. Could you please provide information on how one may obtain access to this dataset?

**Comment by akshaydudhane16** [comment]
Thank you for your interest in our work. Soon we will release our dataset. Stay tuned.

**Comment by NikonD850** [comment]
Greetings! Is the dataset available now? @akshaydudhane16
